services:
  - type: web
    name: haloit-api
    env: docker
    dockerfilePath: ai_connector/Github-Connector/artifacts/api-server/Dockerfile
    branch: main
    plan: free

  - type: web
    name: haloit-msp
    env: docker
    dockerfilePath: halo-system/Dockerfile
    branch: main
    plan: free
